export const GET_ERRORS = 'GET_ERRORS';
export const GET_VENUES= 'GET_VENUES';
export const SEARCH_CHANGED="SEARCH_CHANGED";
export const UPDATE_STATUS_ERROR='UPDATE_STATUS_ERROR';
export const UPDATE_STATUS_SUCCESS="UPDATE_STATUS_SUCCESS";